### ISSUE TITLE
Display total cash held along with denomination

### ISSUE THREAD

**Issue by codeyogi911** [codeyogi911/vmcs_ft02#1]
The system is required to provide an at-a-glance display of the cash amount available, by
denomination, for collection by the Maintainer.
This will enable the Maintainer to readily tally the total cash collected and the total number of coins by denomination displayed in “Show Total Cash Held” and “Press to Collect Cash” when pressed, thus leaving no room for dispute over system errors.

**Comment by codeyogi911** [comment]
Hi team,
There is an enhancement request to the system. This change is required as the maintainer often faces difficulty in tallying the amount dispensed by the machine. In the enhanced scenario, we will be displaying the total amount **along with the denomination.**

**Comment by psablok12345** [comment]
Enhancement verified to be working.

**Comment by codeyogi911** [comment]
Hi team,
Thanks, @Dharith for implementing this.
I have verified the feature to be working as expected.
@RomilaMukherjee let us plan to close this as soon as possible.

**Comment by RomilaMukherjee** [comment]
The Enhancement has been demonstrated to user representative and verified by him.
We mark it close now.
