### ISSUE TITLE
Reset amounts to null after successful logout

### ISSUE THREAD

**Issue by codeyogi911** [codeyogi911/vmcs_ft02#2]
Reset the values to null for “Show Total Cash Held” and “Press to Collect Cash” when the
Maintainer successfully pushes “Press Here When Finished”. The simulation currently does
not clear the values on the completion of a Maintenance session. Upon a subsequent re-login
to the Maintenance Panel in the same session, the cash previously held and already collected,
persists in the display. This sometimes causes confusion to the Maintainer.

**Comment by ragu32** [comment]
Initialization of cash collection and total cash has been done to reset the value.

**Comment by psablok12345** [comment]
I have verified the issue and its has been resolved.

**Comment by RomilaMukherjee** [comment]
Marking the defect closed as defect has been resolved and verified by user representative.
